### ISSUE TITLE
New login from Columbus OH?

### ISSUE THREAD

**Issue by twynne** [bartdorsey/homebridge-blinkcameras#10]
Not accusing here, just asking.  After adding/configuring this plugin I received an automated email from Blink warning of a new sign-in from Columbus OH (I'm in London, UK).

Is there some reason this plugin would result in a remote login to Blink?

**Comment by bartdorsey** [comment]
No. I do not ever receive your login details and you can read the source code to my plugin and the blink-node-security plugin I use to talk to the blink api, as this project is completely open source.

**Comment by twynne** [comment]
Thanks for responding.  Strange... maybe Amazon is somehow routing something through the US?
