### ISSUE TITLE
Blink Deprecation

### ISSUE THREAD

**Issue by rcoletti116** [bartdorsey/homebridge-blinkcameras#11]
Received this today. This plugin is the only 3rd party automation. Will there be a path forward for this integration after 5/11?

Notice: Disabling Unauthorized 3rd Party Automation Scripts
Dear Blink Customer,
--
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. Thank you, | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | Thank you,
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration. | You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration.
You are receiving this email because your account has used automation scripts that use an outdated login method to connect to your Blink account. With security and customer protection as our top priority, that login method is being deprecated.  This means that any scripts you are using will no longer work as of 5/11. We encourage you to try out IFTTT, our supported 3rd party integration, for more secure automation functionality. If you have other feature preferences or requests, you can always email product feedback to info@blinkforhome.com for consideration.
Thank you,

**Comment by bartdorsey** [comment]
Well, that sucks. This would be more a question for the author of `node-blink-security` though. But my guess is, this will kill this plugin and anything built ontop of node-blink-security :( I'll have to do more research to find out.

**Comment by bartdorsey** [comment]
After a bit more digging this apparently is because they are implementing two factor authentication. I wonder if it will be possible to authenticate the plugin using that or not.

**Comment by captconstruct** [comment]
![43D647D2-F6A1-4CDD-9090-7C9CDCD9A5FC](https://user-images.githubusercontent.com/659031/81019971-6e189a00-8e2d-11ea-8e8e-56cf7663077e.jpeg)

**Comment by mtressl** [comment]
Just came here for the same email I got from Blink. Following.

**Comment by Manav-Seth** [comment]
following as well.

**Comment by amiantos** [comment]
I tried out geofencing with IFTTT at one point and it was extremely inconsistent and disappointing. Kind of a shame that's their only "supported" 3rd party integration.

**Comment by Jeremesk** [comment]
I tried to use the Homebridge-ifttt plugin (https://github.com/ilcato/homebridge-ifttt) to create a switch that launches an IFTTT applet (IF Webhooks receives an event X, THEN arm the blink system) and it works.

It's not as seemless as homebridge-blinkcameras but it does the job.

**Comment by mtressl** [comment]
> I tried to use the Homebridge-ifttt plugin (https://github.com/ilcato/homebridge-ifttt) to create a switch that launches an IFTTT applet (IF Webhooks receives an event X, THEN arm the blink system) and it works.
> 
> It's not as seemless as homebridge-blinkcameras but it does the job.

For me IFTTT has horrible and unpredictable response times for Webhooks. Barely usable IMHO.

**Comment by Jeremesk** [comment]
> > I tried to use the Homebridge-ifttt plugin (https://github.com/ilcato/homebridge-ifttt) to create a switch that launches an IFTTT applet (IF Webhooks receives an event X, THEN arm the blink system) and it works.
> > It's not as seemless as homebridge-blinkcameras but it does the job.
> 
> For me IFTTT has horrible and unpredictable response times for Webhooks. Barely usable IMHO.

Well during my tests my system was armed/disarmed pretty instantly.

**Comment by captconstruct** [comment]
Looks like Blink Security has been updated and ready for implementation.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/659031/81428586-0f4f6b00-9122-11ea-9f20-17923e50e5bd.png">

**Comment by bartdorsey** [comment]
I've added support for this in the 2fa branch: Here's a PR containing the changes. If anyone wants to help me test it that would be awesome. https://github.com/bartdorsey/homebridge-blinkcameras/pull/12/files

**Comment by SchneidoDUS** [comment]
I have added **auth_2FA = false** to my confirguration and it immediateky worked again.

**Comment by gdotp01** [comment]
Hi. Can someone help me understand this. I use the plugin "Homebridge Platform Blink Security" which I think is buillt on top of this one ? How does the recent change in Node-blink-security find its way back into the plugins. As of today my authentication stopped working. I tested the IFFT route at the weekend and got it working but its a bit ugly and clunky so would like restore "Homebridge Platform Blink Security" or an alternative to use 2FA

**Comment by bartdorsey** [comment]
This plugin was forked over to Homebridge Platform Blink Security, I merged changes back in but managed to keep the name Homebridge Platform Blink Security in the config.json even though this plugin is called homebridge blinkcameras.  We have a experimental branch `2fa` which enables 2 factor authentication.   

We use the library node-blink-security to talk to the API, the author of that library updated it for 2fa yesterday, so I'll probably be releasing a new version of this plugin today or tomorrow which adds support for 2FA.  I may at that point rename the platform version back to Homebridge Blink Cameras, since it'll require people to edit their config files anyway.

**Comment by yphoenix** [comment]
Looking forward to the official release so that I can upgrade my packages. I updated to the latest node-blink-security and then hand edited the code to include the extra parameters, but would prefer to be able to set them from the config file.

**Comment by bartdorsey** [comment]
This has been released. Please open new issues if you have trouble with 2fa specifically.
