### ISSUE TITLE
System disarmed unexpectedly

### ISSUE THREAD

**Issue by roboterm** [bartdorsey/homebridge-blinkcameras#14]
If I activate the Blink system via Home app, next time I open the app the system is deactivated.

plugin version: v1.0.0
homebridge version: v1.0.4

The plugin was successfully verified as new device before.

**Comment by Venger2005** [comment]
Facing the exact same problem here.  Activate switch in Home app and Blink system correctly arms. But go back into Home app and Blink switch now shows as disarmed, although the Blink system in actual fact remains armed.

**Comment by bartdorsey** [comment]
I'm seeing this as well for just the "Systems". I'm investigating.

**Comment by bartdorsey** [comment]
This PR fixes this problem. 1.0.1 should be out shortly

https://github.com/bartdorsey/homebridge-blinkcameras/pull/16
