### ISSUE TITLE
Duplicates after update

### ISSUE THREAD

**Issue by rcoletti116** [bartdorsey/homebridge-blinkcameras#15]
Does anyone else have their system showing up twice after the v1 update? I removed cached accessories & persist and restarted Homebridge, but still have duplicates of both the system and individual camera devices.

**Comment by bartdorsey** [comment]
This is caused by the Platform changing names and you have old cached accessories. If you have the homebridge web gui you can go into Homebridge Settings and click "Clear cached accessories" and this will get rid of the duplicates.
