### ISSUE TITLE
2fa - enabling

### ISSUE THREAD

**Issue by twynne** [bartdorsey/homebridge-blinkcameras#17]
Trying to figure out where to go to configure the blink system for 2fa. There’s no login option on their website, and nothing in the blink app. Do US users possibly see something different than U.K.?

**Comment by bartdorsey** [comment]
I believe as of May 11th, they are enabling it by default. It sends codes through email.

**Comment by Venger2005** [comment]
> I believe as of May 11th, they are enabling it by default. It sends codes through email.

Not in the UK it doesn’t. All we are receiving here presently is an “authorise this device” email which clicking the link authorises it. But no separate PIN or equivalent code is sent. I’ve also set "auth_2FA": false in my config to stop it potentially asking me to reauthorise devices (I’m not sure if it would do this, but it was more of a precautionary measure).  Hope my local experience helps.

**Comment by bartdorsey** [comment]
So I just noticed as I set this up on my production homebridge that it also did not send me a code to enter. I only got the Allow device email, but once I allowed the device it seems to be working fine.. Interesting.

**Comment by rcoletti116** [comment]
Same here. No code, just Allow Device email. I'm in the U.S.

**Comment by twynne** [comment]
> > I believe as of May 11th, they are enabling it by default. It sends codes through email.
> 
> Not in the UK it doesn’t. All we are receiving here presently is an “authorise this device” email which clicking the link authorises it. But no separate PIN or equivalent code is sent. I’ve also set "auth_2FA": false in my config to stop it potentially asking me to reauthorise devices (I’m not sure if it would do this, but it was more of a precautionary measure). Hope my local experience helps.

I don't see in the docs for this plugin where there's any option to configure 2fa (true/false)... am I missing something?

**Comment by twynne** [comment]
Also the device name set in the config is presumably meant to pass through to the Blink system and appear in the authorisation email.  I get only the device ID showing in my email, device name is generic.

**Comment by Venger2005** [comment]
> Also the device name set in the config is presumably meant to pass through to the Blink system and appear in the authorisation email. I get only the device ID showing in my email, device name is generic.

That’s ‘normal’ as it currently stands

**Comment by Venger2005** [comment]
> I don't see in the docs for this plugin where there's any option to configure 2fa (true/false)... am I missing something?

The option is there in the underlying node-blink-security which this plugin is built from.

**Comment by bartdorsey** [comment]
Yeah, so I had it set to false, because the author seemed to suggest that setting it to `true` would cause the blink API to require a confirmation code EVERY time you authenticate. Which would mean typing in the code every time you restart homebridge. It's possible I misunderstood how this is supposed to work. I can release a version that exposes the 2fa true/false value if that would be useful to anyone.

**Comment by bartdorsey** [comment]
> Also the device name set in the config is presumably meant to pass through to the Blink system and appear in the authorisation email. I get only the device ID showing in my email, device name is generic.

As Venger2005 said, this is currently how the blink emails work. We aren't sure why.

**Comment by bartdorsey** [comment]
In the next release (1.0.4) I'll be exposing this property in the config file.

**Comment by bartdorsey** [comment]
I'm also trying to figure out from the author of node-blink-security if this flag has to be set to `true` the first time you authenticate and then should be turned off for daily use or not.

**Comment by Venger2005** [comment]
Iirc when I authenticated I had the flag already in my config set to false.

**Comment by Sungamm** [comment]
> 
> 
> I'm also trying to figure out from the author of node-blink-security if this flag has to be set to `true` the first time you authenticate and then should be turned off for daily use or not.

Big Thank you for your great work. I was badly surprised about the move from blink and installed your plug-in few minutes ago. Works perfect for me. I received e-Mails from blink, confirm via link and all cameres appears in Homebrige / Homekit. It was not necessary to enter a code (german user). Change config auf discovery to false and reboot. Cameras still active, no new email from blink. Looks perfect for me. Once again, thank you for your great work and sharing this with us!

**Comment by monteroman** [comment]
Interesting.   I did the same thing Sungamm did and I am in the US and did not get the MFA email, but got 2 authentication emails (assuming one for each zone module) and I authorized them and nothing showed up in my Homebridge so I changed the setting to False and restarted HB and I get the dreaded error message I reported on in a previous issue.  :(

**Comment by Manav-Seth** [comment]
I also get the same BlinkAuthenticationException as above, I haven't even gotten any emails.

**Comment by Sungamm** [comment]
Hey Guys,
I dont want to confuse you because I am only a user. But you are running on latest Homebridge version? I cannot see any impact on this with the plug-in but I dont understood why it dont work on your side.

My Homebridge is 1.0.4
Homebridge Blinkcameras is 1.0.3

Give them a trial maybe. 

Good think for me is, its works as in the past. I have some routine that will arm and disarm the cameras in Homekit and this is working again.

**Comment by monteroman** [comment]
HB is 1.0.4 and Blinkcameras is 1.0.3 so it's not that.

**Comment by monteroman** [comment]
Homebridge is now on 1.10 and Blinkcameras is on 1.0.3 and it is still not working sadly.   Just as an FYI.

**Comment by bartdorsey** [comment]
I'm trying to verify from the author of node-blink-security if you EVER need to have 2FA_auth set to true or not. It seems that if you set it to false always and click on the emails to allow the device access it'll 'just work'.  Also if you aren't getting the emails check to make sure they aren't going into your spam folder and that your blink account is using an accurate email address.

**Comment by SchneidoDUS** [comment]
I have to set it up every day again. It looks like Blink is killing the verification every 24 hours. Any ideas to solve it.

**Comment by eskimo** [comment]
> I have to set it up every day again. It looks like Blink is killing the verification every 24 hours. Any ideas to solve it.

Cron job to restart homebridge every 23 hours?

**Comment by brianhackel** [comment]
> I have to set it up every day again. It looks like Blink is killing the verification every 24 hours. Any ideas to solve it.

It would appear in the getBlink() method that the plugin is trying to solve this by taking a timestamp and refreshing the connection (by creating a new Blink (node-blink-security) object every 23 hours and 59 minutes). However, it appears it is not enough to just create a new object; it does not refresh the connection. I'm playing around with adding this._blink.setupSystem() right after the new Blink() object creation in getBlink() after the timeout expires to refresh the Auth Token. Currently, the plugin only calls this once whenever it is reloaded as part of the discover() method. I've had some good results so far testing with a shorter timeout, but i've reset the timeout and I'll know more after 24 hours.

**Comment by brianhackel** [comment]
It would appear from my logs that adding `this._blink.setupSystem()` right after the re-authentication that occurs after the 24 hours expires allows the re-authentication to succeed and not hang my homebridge instance.

**Comment by erickribeiro** [comment]
> It would appear from my logs that adding `this._blink.setupSystem()` right after the re-authentication that occurs after the 24 hours expires allows the re-authentication to succeed and not hang my homebridge instance.

I've been testing this fix locally for approximately 24 hours. So far it appears to work. I'll update the comment if it changes.

**Comment by SchneidoDUS** [comment]
> > I have to set it up every day again. It looks like Blink is killing the verification every 24 hours. Any ideas to solve it.
> 
> Cron job to restart homebridge every 23 hours?

I have added routine that reboots the PI every 24 hours, always in the night at 3. It is working without problems since three days

**Comment by bartdorsey** [comment]
This was being caused by needing to re-authenticate with blink every 24 hours to get a new token. I've fixed this in v1.1.0
