### ISSUE TITLE
Blink Shuts Down Account for Unsupported Log In

### ISSUE THREAD

**Issue by illuminations82** [bartdorsey/homebridge-blinkcameras#25]
When using this plugin, after approximately 10 days, blink disabled my account reporting that this was an unsupported log in and may **only utilize IFTTT or Alexa**.  Once I removed this plugin, they were able to restore my account.

**Comment by gdotp01** [comment]
This is very unfortunate. I’d guess this is Amazon using a security excuse for locking down the cameras to only use Alexa. IFTT is not a solution unfortunately, in Europe it hobbled as a solution with very few options and in general I’ve found it unreliable. I’ll be looking for a more open platform to replace my Blinks.
