### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by erickribeiro** [bartdorsey/homebridge-blinkcameras#31]
Noticed a new issue today after rebooting Homebridge.

```
TypeError: Cannot read property 'message' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/node-blink-security/lib/blink.js:402:90)
    at self.callback (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-blinkcameras/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Node.js Version: v12.16.3
Npm Version: v6.14.5
Homebridge-blinkcameras Version: v1.1.2

**Comment by brianhackel** [comment]
I can verify that at least in the short term (i just made the change), this change helps:
[https://github.com/madshall/node-blink-security/issues/52#issuecomment-656941775](url)

**Comment by yphoenix** [comment]
I can verify that I started seeing this today.

**Comment by mehepiim** [comment]
I can verify also, whole homebridge keeps looping with the same message. Blink seems to require code from email now, how is this handled in login?

**Comment by alekz44** [comment]
Had a problem with the blink plugin as well. Homebridge did not respond and was not available after a reboot.
Deleted the blink plugin and homebridge works again now...

**Comment by mehepiim** [comment]
> 
> 
> Had a problem with the blink plugin as well. Homebridge did not respond and was not available after a reboot.
> Deleted the blink plugin and homebridge works again now...

You can also just remove the config from jason until a fix is found. Im quite sure the issue is with blinks mfa.

**Comment by alekz44** [comment]
> 
> 
> > Had a problem with the blink plugin as well. Homebridge did not respond and was not available after a reboot.
> > Deleted the blink plugin and homebridge works again now...
> 
> You can also just remove the config from jason until a fix is found. Im quite sure the issue is with blinks mfa.

Thanks. I did both, deleted the plugin and edited the config jason. Will keep it in mind for the next time.
yes, problems began after the MFA introduction.

**Comment by ratsoid** [comment]
I removed the code from config.json with Config UI X and it works now.

**Comment by rcoletti116** [comment]
> I can verify that at least in the short term (i just made the change), this change helps:
> [https://github.com/madshall/node-blink-security/issues/52#issuecomment-656941775](url)

This worked for me as well. There is a commit for it and viewing this helped me figure out the last point about "Host": https://github.com/madshall/node-blink-security/commit/7a390a10703c8634ff94896d5ec0b64df7c9741d

**Comment by koweye** [comment]
yes i had this problem as well, removing the plugin fixed everything but thats not really a good solution. please fix

**Comment by ethempekin** [comment]
Why this happens this is really annoying and very unreliable for the system

**Comment by bartdorsey** [comment]
v1.1.4 is out and fixes this. Blink changed the API endpoints on us.
