### ISSUE TITLE
old version 1.1.2 did not work anymore, update to version 1.1.4 failed

### ISSUE THREAD

**Issue by Sungamm** [bartdorsey/homebridge-blinkcameras#33]
Good Morning, 
since Friday the homebridge-blinkcameras plugin did not work anymore. The complete homebridge shutdown. 

I remove the blink configuration from config.json and was able to re-start. Happy to see there is an update availabe (to 1.1.4) but its failed to install

`
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b master git://github.com/madshall/node-blink-security.git /root/.npm/_cacache/tmp/git-clone-e3ddb159
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e3ddb159': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-12T07_23_57_699Z-debug.log

Command failed. Please review log for details.`

Any ideas please?

**Comment by SchneidoDUS** [comment]
Same problem.

**Comment by MasterofKungfu9999** [comment]
Same Problem

**Comment by bartdorsey** [comment]
v1.1.5 fixes this issue.

**Comment by SchneidoDUS** [comment]
> v1.1.5 fixes this issue.

Works! Great. Many thanks
