### ISSUE TITLE
Error platform is not registered after installing and adding to config

### ISSUE THREAD

**Issue by timgris** [bartdorsey/homebridge-blinkcameras#6]
I installed the package, copied the section of the sample config and updated to my user/password.  I am receiving the following error:

Error: The requested platform 'BlinkSecurityPlatform' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)

The section of config I added is:
"platforms" : [                                                                                                                                      
    {                                                                                                                                                  
    "platform": "BlinkSecurityPlatform",                                                                                                               
    "name": "Blink System",                                                                                                                            
    "username" : "<my email>",                                                                                                           
    "password" : "<my password>",                                                                                                               
    "discovery": true                                                                                                                                  
  }                                                                                                                                                    
  ]

**Comment by mokrol** [comment]
When I got this I unstalled and reinstalled and that fixed it.

**Comment by timgris** [comment]
Thank mokrol...I tried uninstalling just the blink package using "sudo npm uninstall homebridge-blinkcameras" and then did a "sudo npm i homebridge-blinkcameras".  Did you uninstall all of homebridge?

Cheers,
Tim

**Comment by timgris** [comment]
After reading about similar issues on other plugins, I found a suggestion to add a "-g" to the install command.  Once I included it, the plugin is now found.  Thanks!
