### ISSUE TITLE
inaccurate armed status

### ISSUE THREAD

**Issue by rcoletti116** [bartdorsey/homebridge-blinkcameras#7]
With the plugin I got my blink system (consisting of just 1 camera) to show up in Homekit/Home app. I will note that the app does show two items, one called blink camera (the name from the config.json) and one with the name of my blink system.

Here's the problem:
When blink is armed, the plugin can successfully disarm it. Home Icon shows On -> Off after press. Switching to Blink app shows the system was in fact disarmed.

However, after this the status in Home returns back to "on" and the controls no longer work. I need to use the blink app to arm it again, after which I can disarm in Home. 

Note: when I use the Homekit controls the homebridge status shows as arm/disarm, but the system itself doesn't change.
Dec 30 22:42:09 raspberrypi homebridge[17313]: [2019-12-30 22:42:09] [Blink System] [blink Camera] is disarmed
Dec 30 22:42:12 raspberrypi homebridge[17313]: [2019-12-30 22:42:12] [Blink System] [blink Camera] arm

**Comment by mtressl** [comment]
For me it helped to turn-off auto discovery. 

`    "discovery": false`

**Comment by pigcooker** [comment]
Having the same type of issue - it shows each individual camera as being armed (always), but seems to switch between saying the whole system is armed or disarmed at random - though in this case the system _is_ armed according to Blink.

```
[1/7/2020, 3:41:32 PM] [Blink System] [Home System] is disarmed
[1/7/2020, 3:41:32 PM] [Blink System] [Front Door Camera] is armed
[1/7/2020, 3:41:32 PM] [Blink System] [Back Door Camera] is armed
```

**Comment by rcoletti116** [comment]
Turning off auto discovery also fixed it for me.

**Comment by pigcooker** [comment]
I have discovery set to false and still get the same result. However, if I restart Homebridge it syncs back up again.

```
[1/7/2020, 4:45:17 PM] [Blink System] [Home System] is armed
[1/7/2020, 4:45:17 PM] [Blink System] [Front Door Camera] is armed
[1/7/2020, 4:45:17 PM] [Blink System] [Back Door Camera] is armed
```

After a few more cycles it will unsync again. Curiously, it always lists the two cameras themselves as 'armed' whether the system is armed or not ... I assume that is for the individual settings for when the system is actually armed?

**Comment by rcoletti116** [comment]
True. It seems the discovery:false only worked for a time. Now it’s back to the same state of being out of sync.

**Comment by bartdorsey** [comment]
I'm assuming what is going on here is that sometimes the blink API returns an error and I'm not catching it properly. I'll look into this maybe this weekend if I have a chance.

**Comment by mtressl** [comment]
Hi @bartdorsey 
were you able to look into this issue? I have a feeling that the status is still not working as expected. Thanks!

**Comment by Venger2005** [comment]
Recently installed this plugin. The 2FA is working perfectly for me but I’m also now faced with this issue (also with discovery set to false) - making it impossible to tell within homekit whether the system is actually armed or disarmed.  Was a solution to this ever found?

**Comment by bartdorsey** [comment]
I believe this is fixed in https://github.com/bartdorsey/homebridge-blinkcameras/pull/16
 
Version 1.0.1 will be released soon with this fix.
